# Generated by Django 4.2.4 on 2023-08-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routes',
            name='end_time',
            field=models.CharField(default='Null', max_length=255),
        ),
        migrations.AddField(
            model_name='routes',
            name='start_time',
            field=models.CharField(default='Null', max_length=255),
        ),
        migrations.AlterField(
            model_name='routes',
            name='car_number',
            field=models.CharField(default='Null', max_length=255),
        ),
        migrations.AlterField(
            model_name='routes',
            name='end_point',
            field=models.CharField(default='Null', max_length=255),
        ),
        migrations.AlterField(
            model_name='routes',
            name='reference_to_geo',
            field=models.TextField(default='Null'),
        ),
        migrations.AlterField(
            model_name='routes',
            name='reference_to_video',
            field=models.TextField(default='Null'),
        ),
        migrations.AlterField(
            model_name='routes',
            name='start_point',
            field=models.CharField(default='Null', max_length=255),
        ),
    ]
