# Generated by Django 4.2.4 on 2023-08-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_routes_end_time_routes_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes',
            name='car_number',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='routes',
            name='end_point',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='routes',
            name='end_time',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='routes',
            name='reference_to_geo',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='routes',
            name='reference_to_video',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='routes',
            name='start_point',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='routes',
            name='start_time',
            field=models.CharField(default='', max_length=255),
        ),
    ]
